
language: python

addons:
  postgresq: "9.4"

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief
    - HTTPD_ERROR_LOG=/var/log/apache2/error.log

before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo service postgresql start 9.4
  - sudo apt-get -y install libpq-dev postgresql-server-dev-9.4 python-dev
  - sudo apt-get -y install chkconfig apache2 ssl-cert libapache2-mod-wsgi python python-dateutil python-ply python-webpy python-tz
  - sudo apt-get purge python-psycopg2
  - sudo pip install web.py
  - sudo pip install psycopg2
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl
  - chkconfig apache2 on
  - cd ..
  - git clone https://github.com/informatics-isi-edu/webauthn.git
  - cd webauthn
  - sudo make install
  - sudo make deploy
  - cd ../ermrest

install:
  - sudo make install PLATFORM=ubuntu1204
  - sudo make deploy PLATFORM=ubuntu1204
  - sudo service apache2 restart
  - sudo ls -l /etc/apache2/conf.d
  - sudo ls -lR /var/run/apache2

before_script:
  - sudo -H -u webauthn webauthn2-manage adduser test1
  - sudo -H -u webauthn webauthn2-manage passwd test1 dummypassword
  - sudo -H -u webauthn webauthn2-manage addattr admin
  - sudo -H -u webauthn webauthn2-manage assign test1 admin

script:
  - sudo ./test/ermrest-registry-purge-tests.sh
  - curl --fail -k -b $COOKIES -c $COOKIES -d username=test1 -d password=dummypassword https://${HOSTNAME}/authn/session
  - bash ./test/rest-tests.sh

after_failure:
  - sudo cat ${HTTPD_ERROR_LOG}
