
language: python

addons:
  postgresq: "9.4"

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief

before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo service postgresql start 9.4
  - sudo apt-get install libpq-dev postgresql-server-dev-9.4 python-dev
  - cd ..
  - git clone https://github.com/informatics-isi-edu/webauthn.git
  - cd webauthn
  - sudo make install PLATFORM=ubuntu1204
  - cd ../ermrest
  - sudo make predeploy PLATFORM=ubuntu1204
  - sudo apt-get purge python-psycopg2
  - sudo pip install psycopg2
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl

install:
  - sudo make install PLATFORM=ubuntu1204
  - sudo make deploy PLATFORM=ubuntu1204

before_script:
  - sudo -H -u ermrest ermrest-webauthn2-manage adduser test1
  - sudo -H -u ermrest ermrest-webauthn2-manage passwd test1 dummypassword
  - sudo -H -u ermrest ermrest-webauthn2-manage addattr admin
  - sudo -H -u ermrest ermrest-webauthn2-manage assign test1 admin

script:
  - sudo ./test/ermrest-registry-purge-tests.sh
  - curl --fail -k -b $COOKIES -c $COOKIES -d username=test1 -d password=dummypassword https://${HOSTNAME}/ermrest/authn/session
  - bash ./test/rest-tests.sh

